### ISSUE TITLE
Failed to setup the openMC and run the example task

### ISSUE THREAD

**Issue by Derek-yfqiu** [spamela/openMC_Marconi#1]
Hi Stan, thanks for the nice work. I got the openMC compiled and installed very smoothly thanks to your script. 

In the step of "python3 setup.py install --user", however, I came across the follow error 

```
Running from scipy source directory.
/cineca/prod/opt/compilers/python/3.6.4/none/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning                                                                                                                                                                   :
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
/cineca/prod/opt/compilers/python/3.6.4/none/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning                                                                                                                                                                   :
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  self.calc_info()
/cineca/prod/opt/compilers/python/3.6.4/none/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning                                                                                                                                                                   :
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  self.calc_info()
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules winreg, win32api or win32con are installed.
error: No lapack/blas resources found. 
``` 

However, I have module the module of lapack/blas in the list: 

```
[****]$ module list
Currently Loaded Modulefiles:
 1) profile/base               7) openmpi/3.0.0--gnu--6.1.0
 2) profile/advanced           8) hdf5/1.8.17--gnu--6.1.0
 3) cmake/3.12.0               9) blas/3.6.0--gnu--6.1.0
 4) gnu/6.1.0                 10) lapack/3.6.1--gnu--6.1.0
 5) zlib/1.2.8--gnu--6.1.0    11) python/3.6.4
 6) szip/2.1--gnu--6.1.0
```

Also the running of the task4 shows the follow error: 
```
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
pytz: No module named 'pytz'
dateutil: No module named 'dateutil'
```

Could you provide some hints? Thanks !

**Comment by makeclean** [comment]
try pip3 install pytz dateutil --user

**Comment by Derek-yfqiu** [comment]
Now I found out the reason. The default python3 in Marconi is python3.5, but openMC setup.py requires python3.6. I load python3.6 and then re-run "python3 setup.py install --user". Perhaps some packages are installed for python3.5 and some are installed for python3.6, so I got the errors. 

I have cleaned the complete folder and start from scratch. Now it works, including the task4. So I suggest @spamela  to specified the python3.6 module in the  "setup_env" script. 

@makeclean I think ```pip3 install pytz dateutil --user``` will also do the job.

**Comment by spamela** [comment]
Hi @Derek-yfqiu and @makeclean 
This is very strange, it works fine for me with python-3.5.
Maybe I have something else in my .bashrc, I will do some more tests and update the script.
By the way, are you planning to use openMC with MOAD/NJOY/DAGMC at some point?
Cheers
Stan

**Comment by spamela** [comment]
Ok, I have the opposite problem: for me it fails with python-3.6

`Invalid MIT-MAGIC-COOKIE-1 keyTraceback (most recent call last):
  File "./example_neutron_flux.py", line 93, in <module>
    fig = plt.subplot()
  File "/marconi/home/userexternal/spamela0/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1075, in subplot
    fig = gcf()
  File "/marconi/home/userexternal/spamela0/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 603, in gcf
    return figure()
  File "/marconi/home/userexternal/spamela0/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 545, in figure
    **kwargs)
  File "/marconi/home/userexternal/spamela0/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 3252, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/marconi/home/userexternal/spamela0/.local/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 950, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/cineca/prod/opt/compilers/python/3.6.4/none/lib/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:104.0"
`

**Comment by Derek-yfqiu** [comment]
That might be some problem: you have to clean all the stuff before using a new python version. Anyway, I am happy at the moment. 
I will work purely with openmc at the moment. Next step I will try the nice csg2csg @makeclean  for converting my MCNP  model.

**Comment by makeclean** [comment]
Great! Let me know if you have any problems on makeclean/csg2csg. In terms of support of openmc it can convert anything, but if you have cones or tori let me know
________________________________

**Comment by Derek-yfqiu** [comment]
If it can convert anything then I am totally happy 😄
